a = input("Enter the first number: ")
b = input("Enter the second number: ")
a=int(a)
b=int(b)
print('\nAddition: ', a+b )
print('Substraction: ', a-b)
print('Multiplication: ', a*b)
print('Division: ', a/b)
